### ISSUE TITLE
Use Test Suites

### ISSUE THREAD

**Issue by projanen** [iu-parfunc/accelerack#1]
Organize testing into Racket's [Test Suites](http://docs.racket-lang.org/rackunit/).

**Comment by rrnewton** [comment]
@pavenvivek and @kylcarte -- I think we can use this ticket to signify putting unit tests in the right place, within the package.  Then we can use `raco` to drive unit tests.

"system tests" can still live outside the package and import it with `(require accelerack)` as needed.

**Comment by pavenvivek** [comment]
Added test suite and initiated 'raco test'

**Comment by rrnewton** [comment]
Nice, thanks!

**Comment by pavenvivek** [comment]
I am not sure whether the unit tests are in right place... We can close this issue after a review...

**Comment by pavenvivek** [comment]
I think this issue is resolved. Closing it..
