### ISSUE TITLE
Write down grammar for the input language of Accelerack

### ISSUE THREAD

**Issue by kylcarte** [iu-parfunc/accelerack#17]

**Comment by rrnewton** [comment]
This should go in a central place in the repo and be referenced by any Racket or Haskell code that deals with the Accelerack-in-Sexp-form representation.

**Comment by rrnewton** [comment]
Clearly, the input/output grammars for the passes (typecheck and normalize) will be different from this initial grammar.

**Comment by rrnewton** [comment]
This is done now for the input language.  Still some work left for the intermediate languages.
