### ISSUE TITLE
Cleanup: for starters, no redundant types.

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/accelerack#22]
Whew, it's hard to know where to start.  This code has layers of renamings and wrappings that are basically deferred refactorings that need to *happen*.

Structs should be defined in one place high up in the module dependence graphs.  There should be one notion of `acc-array?` which we should go ahead and rename `acc-manifest-array?`.  The "racket ops" module must work directly against this manifest type...  which they do, but it needs to be renamed.

Ok, then there are two levels of wrapping, potentially:

 * lifting Racket ops to work over acc-array (sum type) as opposed to acc-manifest-array
 * lifting them to work over normal lists

These can be separate or they can happen in one go.  They're already in there in basically right form, but the name collisions (deferred rename refactors) make it very confusing.

**Comment by rrnewton** [comment]
The C data definitions are all very nice and serve our purposes well.  They just need to be isolated in some module called, e.g. "c_arraydata.rkt".

That module should expose an *absolutely minimal interface* (probably smaller than `acc_allocate` does now), and that should be all the rest of the modules know about CData.

**Comment by rrnewton** [comment]
Most everything in `acc_header` is internal details of the "C data".  But the `define-cstruct _acc-array`... that's currently our `acc-manifest-array?` struct as I understand it.

**Comment by rrnewton** [comment]
Huh, along these lines, I can't remember why we need `rkt-acc-array` in `acc_header.rkt` -- is it still needed?

**Comment by pavenvivek** [comment]
I will remove the rkt-acc-array... They are not needed anymore...

**Comment by rrnewton** [comment]
Great... I think the success criteria will be not needing anymore `require (prefix ...` business.

**Comment by pavenvivek** [comment]
Should racket_ops be able to work over normal lists?  
(acc-map add1 '(1 2 3 4)) is expected to produce '(2 3 4 5)?

**Comment by pavenvivek** [comment]
Almost everything in header.rkt is C data definitions. Should we rename "header.rkt" to "c_arraydata.rkt"?

**Comment by pavenvivek** [comment]
wrappers.rkt provides the necessary wrappers for racket_ops. "prefix-in" requirements are removed for racket_ops functions (they remain only for importing map from racket/base). This issue is fixed. Only thing pending is renaming of "header.rkt" to "c_arraydata.rkt" if necessary. Closing this issue.
