### ISSUE TITLE
Cleanup: eliminate any polymorphism that's just there for a hack.

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/accelerack#25]
(This is related to #22)

Ok, some functions need to be polymorphic in our setup.  For example, over manifest versus delayed data, or over Accelerack data and Racket lists.

HOWEVER, we can't simply have polymorphism around because we have refactors that aren't finished.  I.e. starting with:

```Scheme
(define (foo x) (doX x))
```

And then going to:

```Scheme
(define (foo xy) (if (X? xy) (doX xy) (doY y))) 
```

Because we really want to handle Y, but don't want to change all the code yet.  We need to finish these and get to the final destination:

```Scheme
(define (foo y) (doy y))
```

I'm thinking here of any function that takes a proper `acc-array` but also takes the lower level notion of a manifest array ALSO.

**Comment by pavenvivek** [comment]
A basic question here. What will be there in our delayed array? should it contain any normal non-accelerack data?

**Comment by pavenvivek** [comment]
This issue is fixed.
