### ISSUE TITLE
Cabalize ExInterface.hs / SxpInterface.hs

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/accelerack#29]
It's ok to require the global Cabal install for now.  (Fixing that is the topic of #22.)

But these files should at least install their dependencies via a `cabal install` call rather than manually in the Makefile + raw GHC calls.

@pavenvivek let me know if you need any help with this.

**Comment by prak5190** [comment]
Moved to cabal install and all test cases pass. Closing this issue
