### ISSUE TITLE
v0.3 release checklist - more operators

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/accelerack#50]
0.2 went out already, so these rolled over:

 * [x] while
 * [x] replicate
 * [moved to 0.4] `equal?` support

**Comment by rrnewton** [comment]
replicate is in there but it has an unfortunate restriction to constant extrusion lengths that needs to be fixed

**Comment by vollmerm** [comment]
By restricted to constant extrusion lengths, you mean the amount an array gets replicated in a direction can't be computed from accelerack scalar values?

**Comment by rrnewton** [comment]
Exactly, this messes up Nbody.  Rather than:

```racket
(replicate (r) (r 3) arr)
```

We want to be able to do:

```racket
(let ((len ...))
   (replicate (r) (r len) arr)
```

**Comment by rrnewton** [comment]
Btw.. this syntax is up for debate.  The "all" thing always seemed mysterious.  This lets you "name your dimensions" and then show where the new dimensions fall among them.

**Comment by vollmerm** [comment]
What if `len` were a zero dimensional `acc-array` in that example, rather than an ordinary value? Would that fix the issue?

**Comment by rrnewton** [comment]
Not sure I follow that.  The current code in `racket_ops` assumes that there are only symbols and integers inside the second argument of the replicate syntax.

This named-dimensions version has the complication that it may make users think they can switch the order of the dimensions... e.g. `(replicate (r c) (c r) a)`.  To avoid that we could just use undercores or some other designated symbol (but not "All"):

```Racket
(replicate (_ 3 _) arr)
```

Would be a replicate that takes a 2D array to 3D, introducing a new index in the middle.

**Comment by vollmerm** [comment]
So what's the reason `replicate` is limited to taking only constant arguments? It's that we're expecting literal numbers in the syntax? I guess I'll look into it.

**Comment by rrnewton** [comment]
It was just written very quickly and has that limitation.

**Comment by vollmerm** [comment]
Ah! Okay, sure, that's reasonable. I thought there might have been a more fundamental problem.

**Comment by vollmerm** [comment]
I hacked on the `replicate` macro so it inserts `quote`s around the symbols meant as variables and captures the syntax for anything else. This test passes now:

```racket
(test-equal? "replicate'"
    (let ([x 5])
       (acc-array->sexp
          (replicate () (x)
                        (generate (lambda () 9)))))
    '(9 9 9 9 9))
```
