### ISSUE TITLE
'undefined symbol' when loading haskell .so in acc_rkt/tests/ffi-tests.rkt

### ISSUE THREAD

**Issue by kylcarte** [iu-parfunc/accelerack#9]
To reproduce:

    $ accelerack/validate.sh

Log: http://lpaste.net/144460

**Comment by rrnewton** [comment]
Interesting, what we were seeing today in Sam's office was a missing `stg_forkOnzh` which I thought might have something to do with threaded vs non-threaded runtimes, or just absent runtime libs.

There are some comments on this [on this thread](https://mail.haskell.org/pipermail/haskell-cafe/2012-September/103227.html).  And its possibly similar to [this ticket](https://ghc.haskell.org/trac/ghc/ticket/3807).

But I don't offhand know if there's any guide that tells us how to "properly" build Haskell inside a `.so` while using Cabal to drive the build...

**Comment by rrnewton** [comment]
I think we're past this.  Haskell interop seems ok.
